version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  db:
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: dbpassword
        MYSQL_DATABASE: dbname
        MYSQL_USER: dbusername
        MYSQL_PASSWORD: dbpassword
      volumes:
       - .dbdata:/var/lib/mysql
      ports:
        - "3306:3306"